name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install pytest

    - name: Run tests
      run: pytest

  deploy:
    needs: build-and-test
    if: success() # Deploy only if tests pass
    runs-on: ubuntu-latest

    steps:
    - name: Simulate Deployment
      run: echo "Deploying to production server 🚀"
