name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install pytest

    - name: Run tests
      run: |
        pytest
      # Ajout d'une étape en cas d'échec des tests
      continue-on-error: true

    - name: Notify Slack - Tests Result
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text": "❌ Les tests ont échoué dans le pipeline CI/CD sur main."}' \
        ${{ secrets.SLACK_WEBHOOK_URL }}

      if: success()
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text": "✅ Les tests sont réussis ! Prêt pour le déploiement."}' \
        ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    needs: build-and-test
    if: success() # Deploy only if tests pass
    runs-on: ubuntu-latest

    steps:
    - name: Simulate Deployment
      run: echo "Deploying to production server 🚀"

    - name: Notify Slack - Deployment
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text": "🚀 Déploiement réussi sur la branche main !"}' \
        ${{ secrets.SLACK_WEBHOOK_URL }}
